React Native kaynağı eklendi
fatihacet/turkcekaynaklar-com pull request #389
Opened 2020-11-15 06:19 UTC by vimevim

2020-11-15 20:50 UTC, gokaygurcan commented on README.md
> +- [Türkçe C Kaynakları](https://github.com/vimevim/turkce-c-kaynaklari)
Bu,

2020-11-15 20:51 UTC, gokaygurcan commented on README.md
> +- [Türkçe C# Kaynakları](https://github.com/vimevim/turkce-C-sharp-kaynaklari)
bu,

2020-11-15 20:53 UTC, gokaygurcan requested changes

2020-11-15 20:53 UTC, gokaygurcan commented on README.md
> +- [Türkçe C++ Kaynakları](https://github.com/vimevim/turkce-cpp-kaynaklari)
ve bu zaten #388 ile eklenmedi mi? Neden burada tekrar goruyoruz? `master`'in son halini aldiginizdan emin olur musunuz?

2020-11-23 17:45 UTC, lacivert approved these changes

2020-11-23 17:46 UTC, merged