Çeşitli kaynaklar eklendi.
fatihacet/turkcekaynaklar-com pull request #405
Opened 2021-01-26 19:06 UTC by AbdullahOztuurkk

2021-01-31 13:54 UTC, gokaygurcan requested changes

2021-01-31 13:54 UTC, gokaygurcan commented on README.md
> +- [Swagger Nedir ? .NET Core Swagger Entegrasyonu](https://medium.com/gdgsivas/swagger-nedir-net-core-swagger-entegrasyonu-67c678f8056a) - [Abdullah Öztürk](https://abdullahozturkk.medium.com/)
Soru isaretinden once bosluk kullanilmaz, kaldirirsaniz okumasi daha kolay bir sekle donusur.

2021-01-31 20:06 UTC, AbdullahOztuurkk commented on README.md
> +- [Swagger Nedir ? .NET Core Swagger Entegrasyonu](https://medium.com/gdgsivas/swagger-nedir-net-core-swagger-entegrasyonu-67c678f8056a) - [Abdullah Öztürk](https://abdullahozturkk.medium.com/)
Hemen düzelteyim , gözümden kaçmış.

2021-02-01 11:18 UTC, gokaygurcan approved these changes

2021-02-01 11:18 UTC, merged

2021-02-01 11:18 UTC, gokaygurcan commented
Tesekkurler ^_^