Javascript ve Vue.js içerikleri eklendi
fatihacet/turkcekaynaklar-com pull request #406
Opened 2021-01-27 17:03 UTC by mustafacagri

2021-01-31 13:53 UTC, gokaygurcan requested changes
Javascript'leri JavaScript olarak degistirir, bir de Vue.js mi yoksa Vue.JS mi konusuna karar verirsek harika bir pr olur bundan.

2021-02-02 10:16 UTC, mustafacagri commented
> Javascript'leri JavaScript olarak degistirir, bir de Vue.js mi yoksa Vue.JS mi konusuna karar verirsek harika bir pr olur bundan.

Yorum için teşekkürler @gokaygurcan

2021-06-23 09:19 UTC, gokaygurcan requested changes

2021-06-23 09:19 UTC, gokaygurcan commented on README.md
> +- [JavaScript Array Fonksiyonları ve Örnekleri](https://www.mustafacagri.com/javascript-array-fonksiyonlari) - [Mustafa Çağrı Güven](https://www.mustafacagri.com/)
Bu link sanirim serinin baslangici ve diger tum yazilari iceriyor (ya da icerecek).

2021-06-23 09:19 UTC, gokaygurcan commented on README.md
> +- [JavaScript’te .find() Array Fonksiyonu](https://www.mustafacagri.com/javascriptte-find-array-fonksiyonu) - [Mustafa Çağrı Güven](https://www.mustafacagri.com/)
Eger durum yukaridaki gibiyse, bu link'e ihtiyac yok. Cunku zaten ilk link herhangi bir bilgi sunmuyor, diger icerikler icin zemin hazirliyor.

2021-06-23 09:19 UTC, gokaygurcan commented on README.md
> +- [Vue.js Dersleri](https://www.mustafacagri.com/frontend/vue-js-dersleri) - [Mustafa Çağrı Güven](https://www.mustafacagri.com/)
Ayni durum burada da mevcut. Zaten bu link diger tum iceriklere erismeyi sagliyor, asagida tekrar hepsini listelemenin pek de bir faydasi yok.

2023-01-29 17:23 UTC, closed without merging