Git - Basit Rehber linki eklendi.
fatihacet/turkcekaynaklar-com pull request #409
Opened 2021-01-31 22:30 UTC by hamzaazman

2021-02-01 11:18 UTC, gokaygurcan requested changes

2021-02-01 11:18 UTC, gokaygurcan commented on README.md
> +- [Git - Basit Rehber](http://rogerdudler.github.io/git-guide/index.tr.html)
https ile degistirebilir miyiz? varken https halini kullanmamak olmaz.

2021-02-01 14:35 UTC, hamzaazman commented on README.md
> +- [Git - Basit Rehber](http://rogerdudler.github.io/git-guide/index.tr.html)
Https olarak bulamadım ama farklı içerikler bulup katkı sağlamaya çalışırım.

2021-02-01 23:05 UTC, gokaygurcan commented on README.md
> +- [Git - Basit Rehber](http://rogerdudler.github.io/git-guide/index.tr.html)
http kismini https olarak degistirmeniz yeterliydi :(

2021-02-02 12:03 UTC, hamzaazman commented on README.md
> +- [Git - Basit Rehber](http://rogerdudler.github.io/git-guide/index.tr.html)
Yeniyim buralarda. Öğrenmiş oldum teşekkürler :)

2021-02-02 12:49 UTC, gokaygurcan commented on README.md
> +- [Git - Basit Rehber](http://rogerdudler.github.io/git-guide/index.tr.html)
haha uzgunum, daha acik yazsaymisim keske :)

2021-02-02 14:25 UTC, closed without merging