Hiç bilmeyenler için veri bilimi videosu eklendi.
fatihacet/turkcekaynaklar-com pull request #447
Opened 2022-03-02 22:12 UTC by bilalbozkurt

- Veri Bilimi başlığına `Hiç Bilmeyenler için Veri Bilimi` videosu eklendi.

2022-03-08 09:29 UTC, gokaygurcan requested changes

2022-03-08 09:29 UTC, gokaygurcan commented on README.md
> +- [Veri Madenciliği (Hiç Bilmeyenler için)](https://youtu.be/yeXIwwDEHvA) - [Şadi Evren Şeker](http://sadievrenseker.com)
Vidyo iceriklerin basina ekledigimiz 🎥  gibi bir icon var, onu da ekler misiniz?

2022-03-09 15:43 UTC, bilalbozkurt commented on README.md
> +- [Veri Madenciliği (Hiç Bilmeyenler için)](https://youtu.be/yeXIwwDEHvA) - [Şadi Evren Şeker](http://sadievrenseker.com)
Güncelledim.

2022-03-09 15:44 UTC, bilalbozkurt commented
İstenilen değişiklik yapıldı. Review bekleniyor.

2022-03-11 22:55 UTC, gokaygurcan approved these changes

2022-03-11 22:55 UTC, merged

2022-03-11 22:55 UTC, gokaygurcan commented
Tesekkurler