"Gömülü Sistemler" eklendi.
fatihacet/turkcekaynaklar-com pull request #449
Opened 2022-03-04 09:41 UTC by sahinenes

2022-03-06 16:45 UTC, burakturkoglu5454 commented
gh pr checkout 449

2022-03-08 09:28 UTC, gokaygurcan requested changes

2022-03-08 09:28 UTC, gokaygurcan commented on README.md
> +- [C ile AVR Mikrodenetleyici Programlama - ATmega328p ve  Arduino (36- Kısım)](https://www.youtube.com/playlist?list=PL2dZ_nzb8WtnivT5Fyou_LrEcmR-Yy6y_) -
"Soner Ayar" ismi 338. satirda kalmak yerine 339. satira tasmis. 

Vidyo olan icerikler icin 🎥  gibi bir sey kullaniyorduk, ona bi bakip eklerseniz harika olur.

Son olarak, "ATmega328p ve  Arduino" kisminda gereksiz bir bosluk var.

2022-03-08 09:28 UTC, gokaygurcan commented on README.md
> +- [C ile AVR Microcontroller Programlama - Haberleşme](https://www.youtube.com/playlist?list=PL2dZ_nzb8WtnNM4Hd1TenNSexoEciz4xp) - Soner Ayar
"Soner Ayar" ismi 338. satirda kalmak yerine 339. satira tasmis.

Vidyo olan icerikler icin 🎥 gibi bir sey kullaniyorduk, ona bi bakip eklerseniz harika olur.

Son olarak, "ATmega328p ve Arduino" kisminda gereksiz bir bosluk var.

2022-03-08 09:28 UTC, gokaygurcan commented on README.md
> +- [C ile AVR Microcontroller Programlama - Haberleşme](https://www.youtube.com/playlist?list=PL2dZ_nzb8WtnNM4Hd1TenNSexoEciz4xp) - Soner Ayar
"Soner Ayar" ismi 338. satirda kalmak yerine 339. satira tasmis.

Vidyo olan icerikler icin 🎥 gibi bir sey kullaniyorduk, ona bi bakip eklerseniz harika olur.

Son olarak, "ATmega328p ve Arduino" kisminda gereksiz bir bosluk var.

2022-03-11 22:56 UTC, gokaygurcan approved these changes

2022-03-11 22:56 UTC, merged

2022-03-11 22:56 UTC, gokaygurcan commented
Tesekkurler